---
- include: common.yml

- include: cpu.yml
  when: collectd_cpu == True

- include: curl.yml
  when: collectd_curl == True

- include: df.yml
  when: collectd_df == True

- include: disk.yml
  when: collectd_disk == True

- include: entropy.yml
  when: collectd_entropy == True

- include: interface.yml
  when: collectd_interface == True

- include: load.yml
  when: collectd_load == True

- include: memory.yml
  when: collectd_memory == True

- include: mysql.yml
  when: collectd_mysql == True

- include: network.yml
  when: collectd_network_server == True or collectd_network_client == True

- include: ping.yml
  when: collectd_ping == True

- include: port_check.yml
  when: collectd_port_check == True

- include: processes.yml
  when: collectd_processes == True

- include: python_systemd.yml
  when: collectd_systemd == True

- include: swap.yml
  when: collectd_swap == True

- include: tail.yml
  when: collectd_tail == True

- include: uptime.yml
  when: collectd_uptime == True

- include: users.yml
  when: collectd_users == True

- include: write_graphite.yml
  when: collectd_write_graphite == True