---
- include: docker.yml

- name: Install BIND on DNS server node
  hosts: dns_server
  remote_user: root
  vars:
    zones:
      -
       zone_name: "{{ mgmt_dns_domain }}"
       zone_filename: "{{ mgmt_dns_domain }}.zone"
       primary_dns: "{{ mgmt_dns_primary_name }}"
       primary_dns_ip: "{{ mgmt_dns_primary_ip }}"
       serial_number: 2017042601
       refresh_interval: 21600
       retry_interval: 3600
       expire_interval: 604800
       min_ttl: 86400

  roles:
    - bind

- name: Install docker DDNS container to all docker nodes
  hosts: docker
  roles:
    - docker_ddns
