---
- include: docker.yml

- name: Install BIND on DNS server node
  hosts: dns_server
  remote_user: root
  vars_files:
    - group_vars/{{ groupname }}.yml
  roles:
    - bind

- name: Install docker DDNS container to all docker nodes
  hosts: docker
  vars_files:
    - group_vars/{{ groupname }}.yml
  roles:
    - docker_ddns
