---
- include: dns.yml

- name: |
    Install full-fledged monitoring stack based on Prometheus, Graphite and
    Grafana. Alerting is done via Alertmanager (part of the Prometheus), data
    exporting to Graphite is done via graphite-bridge.
  hosts: monitoring
  remote_user: root
  vars:
    alertmanager_host: "alertmanager.{{ mgmt_dns_domain }}"
    docker_grafana_labels:
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.{{ mgmt_dns_domain }}"
    docker_graphite_exporter_labels:
      - "traefik.backend=graphite-exporter"
      - "traefik.frontend.rule=Host:graphite-exporter.{{ mgmt_dns_domain }}"
      - "traefik.enable=false"
    docker_alertmanager_labels:
      - "traefik.backend=alertmanager"
      - "traefik.frontend.rule=Host:alertmanager.{{ mgmt_dns_domain }}"
      - "traefik.enable=false"
    docker_graphite_labels:
      - "traefik.backend=graphite"
      - "traefik.frontend.rule=Host:graphite.{{ mgmt_dns_domain }}"
      - "traefik.enable=false"
    docker_prometheus_labels:
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.{{ mgmt_dns_domain }}"
      - "traefik.enable=false"
  vars_files:
    - group_vars/{{ groupname }}.yml
  roles:
    - graphite
    - graphite_exporter
    - grafana
    - { name: alertmanager, tags: alertmanager }
    - { name: prometheus, tags: prometheus }

- name: Install collectd into all the nodes
  tags: collectd
  hosts: all
  remote_user: root
  vars:
    collectd_interval: 10
    graphite_hosts:
      graphite_host:
        hostname: "graphite.{{ mgmt_dns_domain }}"
        port: 2003
      graphite_exporter_host:
        hostname: "graphite-exporter.{{ mgmt_dns_domain }}"
        port: 9109
  vars_files:
    - group_vars/{{ groupname }}.yml
  roles:
    - collectd
