---
keys_directory: /var/named/keys
dns_allow_nets: localnets
be_forward_server: true
dns_forwarders:
  - 8.8.8.8
  - 8.8.4.4
zones:
    -
     zone_name: "{{ mgmt_dns_domain }}"
     zone_filename: "{{ mgmt_dns_domain }}.zone"
     primary_dns: "{{ mgmt_dns_primary_name }}"
     primary_dns_ip: "{{ mgmt_dns_primary_ip }}"
     serial_number: 2017042601
     refresh_interval: 21600
     retry_interval: 3600
     expire_interval: 604800
     min_ttl: 86400
